run:
  experiment_type: "evaluate"
  rng_seed: 43

network: "smallart^sf3"
twins: "examples/find/smallart/sf3/logs/8"

evaluator:
  out_dir: "./examples/evaluate"
  divergency: [
    "R",
    "tau",
    "r",
    "gamma",
    "beta",
    "xi",
  ]
