run:
  experiment_type: "evaluate"
  rng_seed: 43

original_network: "bigreal^Freebase"
layer_map: "./examples/find/smallart/sf3/lmap.json"
twin_networks: [
  "mabcd^./examples/find/smallart/sf3/logs/17/*",
]

evaluator:
  out_dir: "./examples/evaluate"
  divergencies: [
    "R_edges_correlation",
    "tau_degrees_correlation",
    "r_communities_correlation",
    "gamma_degree_distribution",
    "beta_community_sizes_distribution",
    "xi_intercommunity_noise",
  ]
