run:
  experiment_type: "generate"
  rng_seed: 42

mln_config:
  params_path: "./experiments/find_rudimentary/bigreal/Freebase/config.yaml" # configuration parameters file
  d_max_iter: 1000 # all parameters defined explicitly will overwrite those in the params_path file
  c_max_iter: 1000
  t: 100
  eps: 0.05
  d: 1
  edges_filename: twin_edges_d1.dat
  communities_filename: twin_communities_d1.dat

generator:
  repetitions: 10
  out_dir: "./experiments/experiment_d/bigreal/Freebase/twins"
