run:
  experiment_type: "evaluate"
  rng_seed: 42

original_network: "bigreal^Freebase"
layer_map: "./experiments/experiment_finder_method/rudimentary/bigreal/Freebase/lmap.json"
twin_networks: [
  "mabcd^./experiments/experiment_finder_method/rudimentary/bigreal/Freebase/twins/twin_edges*",
]

evaluator:
  out_dir: "./experiments/experiment_finder_method/rudimentary/bigreal/Freebase/evaluate"
  divergencies: [
    "R_edges_correlation",
    "tau_degrees_correlation",
    "r_communities_correlation",
    "gamma_degree_distribution",
    "beta_community_sizes_distribution",
    "xi_intercommunity_noise",
  ]
