run:
  experiment_type: "generate"
  rng_seed: 43

mln_config:
  params_path: "./examples/generate/example_twin_config.yaml" # configuration parameters file
  d_max_iter: 1000 # all parameters defined explicitly will overwrite those in the params_path file
  c_max_iter: 1000
  t: 100
  eps: 0.05
  d: 2
  edges_filename: edges.dat
  communities_filename: communities.dat

generator:
  repetitions: 5
  out_dir: "./examples/generate"
